# Generated by Django 3.1.5 on 2021-02-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tegs',
            new_name='tags',
        ),
    ]
